const posts = [
  {
    id: 1,
    userName: "John Doe",
    time: 1727785341917,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 32,
    commentCount: 5,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 2,
    userName: "Fredie",
    time: 1727711080249,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 11,
    commentCount: 3,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 3,
    userName: "Zara",
    time: 1721781080249,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 123,
    commentCount: 52,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 4,
    userName: "John Doe",
    time: 1727785341917,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 32,
    commentCount: 5,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 5,
    userName: "Fredie",
    time: 1727711080249,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 11,
    commentCount: 3,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 6,
    userName: "Zara",
    time: 1721781080249,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 123,
    commentCount: 52,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 7,
    userName: "John Doe",
    time: 1727785341917,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 32,
    commentCount: 5,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 8,
    userName: "Fredie",
    time: 1727711080249,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 11,
    commentCount: 3,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 2123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
  {
    id: 9,
    userName: "Zara",
    time: 1721781080249,
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    likeCount: 123,
    commentCount: 52,
    comments: [
      {
        id: 123,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 3232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 22123,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
      {
        id: 12223,
        userName: "Jeremy",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 2,
        dislikeCount: 1,
      },
      {
        id: 322232,
        userName: "Sona",
        time: 1727785342000,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 4,
        dislikeCount: 5,
      },
      {
        id: 212223,
        userName: "Zack",
        time: 1727785341917,
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        likeCount: 3,
        dislikeCount: 2,
      },
    ],
  },
];

export default posts;
